Test

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -107,12 +107,12 @@ jobs:
           exit 1
         continue-on-error: true
 
-      # Ensure previous test indeed failed (it continues on error but also continues on success ...)
-      - name: Make sure the previous step has failed
-        if: ${{ steps.failure.outcome == 'success' }}
-        run: |
-          echo "The previous step with an explicit failure should have failed while it succeeded"
-          exit 1
+#      # Ensure previous test indeed failed (it continues on error but also continues on success ...)
+#      - name: Make sure the previous step has failed
+#        if: ${{ steps.failure.outcome == 'success' }}
+#        run: |
+#          echo "The previous step with an explicit failure should have failed while it succeeded"
+#          exit 1
 
       # This should check that a dump has been created in the github workspace, check its content (?)
       # and then remove it
